# Usa a imagem oficial do Node.js como base
FROM node:20

# Define o diretório de trabalho
WORKDIR /app

# Instala o Angular CLI globalmente
RUN npm install -g @angular/cli@19

# Expõe a porta padrão do Angular (4200)
EXPOSE 4200

# Comando para manter o container ativo e permitir interação
CMD ["bash"]